// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzkolkaRoslin_API.Controllers.Data;

#nullable disable

namespace SzkolkaRoslin_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SzkolkaRoslin_API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegancka roślina doniczkowa idealna do salonu. Łatwa w pielęgnacji, oczyszcza powietrze.",
                            ImageUrl = "https://example.com/images/fikus-benjamina.jpg",
                            Name = "Fikus Benjamina",
                            Price = 49.990000000000002,
                            UpdatedDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Popularna roślina tropikalna o charakterystycznych dziurawych liściach. Idealna do jasnych pomieszczeń.",
                            ImageUrl = "https://example.com/images/monstera.jpg",
                            Name = "Monstera Deliciosa",
                            Price = 79.989999999999995,
                            UpdatedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wysokiej jakości ziemia do większości roślin doniczkowych i ogrodowych.",
                            ImageUrl = "https://example.com/images/podloze.jpg",
                            Name = "Podłoże uniwersalne 10L",
                            Price = 19.989999999999998,
                            UpdatedDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Płynny nawóz mineralny wspomagający wzrost i intensywność koloru liści. Pojemność 500ml.",
                            ImageUrl = "https://example.com/images/nawoz.jpg",
                            Name = "Nawóz do roślin zielonych",
                            Price = 24.989999999999998,
                            UpdatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ręcznie robiona doniczka ceramiczna z podstawką. Dostępna w kolorze terakoty.",
                            ImageUrl = "https://example.com/images/doniczka.jpg",
                            Name = "Doniczka ceramiczna 20cm",
                            Price = 34.990000000000002,
                            UpdatedDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
